name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@main

      - name: Delete old files
        run: |
          cd ${{ github.workspace }}
          find * | grep -v ".github" | xargs rm -rf
        
      - name: Checkout Levilde-Luminia-Wiki
        uses: actions/checkout@main
        with:
          repository: BsBlog/Levilde-Luminia-Wiki
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: Levilde-Luminia-Wiki
          
      - name: Setup pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest
          
      - name: Install dependencies
        working-directory: Levilde-Luminia-Wiki
        run: pnpm install

      - name: Build docs
        working-directory: Levilde-Luminia-Wiki
        run: pnpm docs:build

      - name: Copy dist files
        run: |
          cp -r ${{ github.workspace }}/Levilde-Luminia-Wiki/src/.vuepress/dist/* ${{ github.workspace }}
          rm -rf ${{ github.workspace }}/Levilde-Luminia-Wiki
          cd ${{ github.workspace }}
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "docs: update documentation"
          git push origin main

      - name: Deploy to Retinbox Web Hosting
        uses: rthsoftware/host-auto-deploy@master
        env:
          RTH_API_KEY: ${{ secrets.RTH_API_KEY }}
        with:
          site: "levilde-luminia-wiki"  # 修改 example 为您的网站名称
          outdir: "."  # 修改 dist 为您的构建输出目录

      - name: Deploy to Retinbox Web Hosting
        uses: rthsoftware/host-auto-deploy@master
        env:
          RTH_API_KEY: ${{ secrets.RTH_API_KEY }}
        with:
          site: "wiki.itsmyduty.top"  # 修改 example 为您的网站名称
          outdir: "."  # 修改 dist 为您的构建输出目录

      - name: Delete old workflow run
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
