name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@main
        with:
         fetch-depth: 0

      - name: Delete old files
        continue-on-error: true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          ls -A | grep -v "\.git" | grep -v "\.github" | xargs rm -rf
          git add -A
          git commit -m "docs: Delete old files"
          git push origin main

      - name: Checkout Levilde-Luminia-Wiki
        uses: actions/checkout@main
        with:
          repository: BsBlog/Levilde-Luminia-Wiki
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          path: Levilde-Luminia-Wiki
          
      - name: Setup pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest
          
      - name: Install dependencies
        working-directory: Levilde-Luminia-Wiki
        run: pnpm install

      - name: Build docs
        working-directory: Levilde-Luminia-Wiki
        run: pnpm docs:build

      - name: Copy dist files
        continue-on-error: true
        run: |
          cp -r ${{ github.workspace }}/Levilde-Luminia-Wiki/src/.vuepress/dist/* ${{ github.workspace }}
          rm -rf ${{ github.workspace }}/Levilde-Luminia-Wiki
          cd ${{ github.workspace }}
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "docs: update documentation"
          git push origin main
          
      - name: Deploy via Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ github.workspace }} --project-name=levilde-luminia-wiki-dist

      - name: Delete old workflow run
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
